In [2]:
import yfinance as yf

df = yf.download("AAPL", start = "2015-01-01")
df.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.192602  24.659504  23.754466  24.648440  212818400
2015-01-05  23.511055  24.042129  23.325180  23.962467  257142000
2015-01-06  23.513275  23.772173  23.152587  23.575233  263188400
2015-01-07  23.842985  23.942561  23.610640  23.721280  160423600
2015-01-08  24.759087  24.816620  24.053201  24.170481  237458000

In [3]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2891 entries, 2015-01-02 to 2026-07-02
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   2891 non-null   float64
 1   (High, AAPL)    2891 non-null   float64
 2   (Low, AAPL)     2891 non-null   float64
 3   (Open, AAPL)    2891 non-null   float64
 4   (Volume, AAPL)  2891 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 135.5 KB

In [4]:
df.isna().sum()

Price   Ticker
Close   AAPL      0
High    AAPL      0
Low     AAPL      0
Open    AAPL      0
Volume  AAPL      0
dtype: int64

In [5]:
df.columns

MultiIndex([( 'Close', 'AAPL'),
            (  'High', 'AAPL'),
            (   'Low', 'AAPL'),
            (  'Open', 'AAPL'),
            ('Volume', 'AAPL')],
           names=['Price', 'Ticker'])

In [6]:
tickers = ["AAPL", "MSFT", "JPM", "XOM", "PFE"]
data = yf.download(tickers, start="2015-01-01")
data.columns

[*********************100%***********************]  5 of 5 completed

MultiIndex([( 'Close', 'AAPL'),
            ( 'Close',  'JPM'),
            ( 'Close', 'MSFT'),
            ( 'Close',  'PFE'),
            ( 'Close',  'XOM'),
            (  'High', 'AAPL'),
            (  'High',  'JPM'),
            (  'High', 'MSFT'),
            (  'High',  'PFE'),
            (  'High',  'XOM'),
            (   'Low', 'AAPL'),
            (   'Low',  'JPM'),
            (   'Low', 'MSFT'),
            (   'Low',  'PFE'),
            (   'Low',  'XOM'),
            (  'Open', 'AAPL'),
            (  'Open',  'JPM'),
            (  'Open', 'MSFT'),
            (  'Open',  'PFE'),
            (  'Open',  'XOM'),
            ('Volume', 'AAPL'),
            ('Volume',  'JPM'),
            ('Volume', 'MSFT'),
            ('Volume',  'PFE'),
            ('Volume',  'XOM')],
           names=['Price', 'Ticker'])

In [7]:
data['Close'].head()

Ticker           AAPL        JPM       MSFT        PFE        XOM
Date
2015-01-02  24.192600  46.274315  39.681736  18.082529  57.145557
2015-01-05  23.511059  44.837727  39.316830  17.984411  55.581951
2015-01-06  23.513271  43.675129  38.739777  18.134474  55.286449
2015-01-07  23.842979  43.741776  39.231979  18.382660  55.846645
2015-01-08  24.759081  44.719242  40.386108  18.757811  56.776180

In [8]:
import sys
sys.path.append('..')

from data import fetch_data

In [9]:
data = fetch_data(tickers)
data["AAPL"].head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Date
2015-01-02  24.192600  24.659502  23.754464  24.648438  212818400
2015-01-05  23.511066  24.042140  23.325192  23.962479  257142000
2015-01-06  23.513268  23.772165  23.152579  23.575226  263188400
2015-01-07  23.842979  23.942555  23.610634  23.721274  160423600
2015-01-08  24.759083  24.816616  24.053197  24.170477  237458000

In [10]:
data = fetch_data(tickers)
data["AAPL"].head()

                Close       High        Low       Open     Volume
Date
2015-01-02  24.192600  24.659502  23.754464  24.648438  212818400
2015-01-05  23.511066  24.042140  23.325192  23.962479  257142000
2015-01-06  23.513268  23.772165  23.152579  23.575226  263188400
2015-01-07  23.842979  23.942555  23.610634  23.721274  160423600
2015-01-08  24.759083  24.816616  24.053197  24.170477  237458000

In [11]:
data = fetch_data(tickers)
data["AAPL"].head()

                Close       High        Low       Open     Volume
Date
2015-01-02  24.192600  24.659502  23.754464  24.648438  212818400
2015-01-05  23.511066  24.042140  23.325192  23.962479  257142000
2015-01-06  23.513268  23.772165  23.152579  23.575226  263188400
2015-01-07  23.842979  23.942555  23.610634  23.721274  160423600
2015-01-08  24.759083  24.816616  24.053197  24.170477  237458000

In [12]:
data = fetch_data(tickers)
data["MSFT"].head()

                Close       High        Low       Open    Volume
Date
2015-01-02  39.681740  40.241833  39.495044  39.596879  27913900
2015-01-05  39.316833  39.656282  39.248942  39.350776  39673900
2015-01-06  38.739750  39.673237  38.646401  39.359246  36447900
2015-01-07  39.231972  39.427155  38.603990  39.019815  29114100
2015-01-08  40.386105  40.521885  39.647801  39.673259  29645200